use num_bigint::BigUint;
use soroban_poseidon::{poseidon2_hash, Field};
use soroban_sdk::{crypto::BnScalar, Bytes, Env, Vec as SorobanVec, U256};
use std::{fs, path::Path};

const TREE_DEPTH: usize = 4;
const INVOICE_HASH: u64 = 0x01ce_2026;
const MIN_TOTAL_CENTS: u64 = 1_200_000;
const MIN_PAID_COUNT: u32 = 12;
const PERIOD_BUCKET: u32 = 202_606;

struct Persona {
    name: &'static str,
    payee_hash: u64,
    aggregate_total_cents: u64,
    paid_invoice_count: u32,
    credential_secret: u64,
    salt: u64,
}

fn personas() -> [Persona; 2] {
    [
        Persona {
            name: "qualified",
            payee_hash: 0xa11ce001,
            aggregate_total_cents: 1_845_000,
            paid_invoice_count: 27,
            credential_secret: 0x123456,
            salt: 0xabcdef,
        },
        Persona {
            name: "unqualified",
            payee_hash: 0x0badc0de,
            aggregate_total_cents: 420_000,
            paid_invoice_count: 5,
            credential_secret: 0x654321,
            salt: 0xc0ffee,
        },
    ]
}

fn be32_from_biguint(x: &BigUint) -> [u8; 32] {
    let mut be = x.to_bytes_be();
    if be.len() > 32 {
        be = be[be.len() - 32..].to_vec();
    }
    let mut out = [0u8; 32];
    let start = 32 - be.len();
    out[start..].copy_from_slice(&be);
    out
}

fn field_hash(env: &Env, inputs: &[BigUint]) -> BigUint {
    let modulus = <BnScalar as Field>::modulus(env);
    let mut vec = SorobanVec::new(env);
    for input in inputs {
        let bytes = Bytes::from_array(env, &be32_from_biguint(input));
        vec.push_back(U256::from_be_bytes(env, &bytes).rem_euclid(&modulus));
    }
    let out = poseidon2_hash::<4, BnScalar>(env, &vec);
    let out_bytes = out.to_be_bytes();
    let mut out_arr = [0u8; 32];
    out_bytes.copy_into_slice(&mut out_arr);
    BigUint::from_bytes_be(&out_arr)
}

fn zero_at(env: &Env, level: usize) -> BigUint {
    let mut z = BigUint::from(0u32);
    for _ in 0..level {
        z = field_hash(env, &[z.clone(), z.clone()]);
    }
    z
}

fn compute_root(env: &Env, leaf: &BigUint, siblings: &[BigUint]) -> BigUint {
    let mut cur = leaf.clone();
    for sibling in siblings {
        cur = field_hash(env, &[cur, sibling.clone()]);
    }
    cur
}

fn list(values: &[BigUint]) -> String {
    values
        .iter()
        .map(|value| format!("\"{}\"", value))
        .collect::<Vec<_>>()
        .join(", ")
}

fn write_persona(root: &Path, env: &Env, persona: &Persona) {
    let invoice_hash = BigUint::from(INVOICE_HASH);
    let payee_hash = BigUint::from(persona.payee_hash);
    let aggregate = BigUint::from(persona.aggregate_total_cents);
    let paid_count = BigUint::from(persona.paid_invoice_count);
    let period = BigUint::from(PERIOD_BUCKET);
    let secret = BigUint::from(persona.credential_secret);
    let salt = BigUint::from(persona.salt);
    let siblings: Vec<BigUint> = (0..TREE_DEPTH).map(|i| zero_at(env, i)).collect();
    let leaf = field_hash(
        env,
        &[
            payee_hash.clone(),
            aggregate.clone(),
            paid_count.clone(),
            period.clone(),
            secret.clone(),
            salt.clone(),
        ],
    );
    let root_value = compute_root(env, &leaf, &siblings);
    let nullifier = field_hash(env, &[secret.clone(), invoice_hash.clone()]);
    let bits = vec![BigUint::from(0u32); TREE_DEPTH];

    let content = format!(
        "# Generated by contracts/proofpay/examples/populate_publics.rs\n\
root = \"{root_value}\"\n\
payee_hash = \"{payee_hash}\"\n\
invoice_hash = \"{invoice_hash}\"\n\
min_total_cents = \"{MIN_TOTAL_CENTS}\"\n\
min_paid_count = \"{MIN_PAID_COUNT}\"\n\
period_bucket = \"{PERIOD_BUCKET}\"\n\
nullifier = \"{nullifier}\"\n\
aggregate_total_cents = \"{}\"\n\
paid_invoice_count = \"{}\"\n\
credential_secret = \"{}\"\n\
salt = \"{}\"\n\
path_siblings = [{}]\n\
path_bits = [{}]\n",
        persona.aggregate_total_cents,
        persona.paid_invoice_count,
        persona.credential_secret,
        persona.salt,
        list(&siblings),
        list(&bits),
    );

    let proofpay_dir = root.join("circuits/proofpay");
    fs::write(
        proofpay_dir.join(format!("Prover.{}.toml", persona.name)),
        &content,
    )
    .expect("write persona prover");
    if persona.name == "qualified" {
        fs::write(proofpay_dir.join("Prover.toml"), content).expect("write active prover");
    }
}

fn main() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("workspace root");
    for persona in personas() {
        write_persona(root, &env, &persona);
    }
    println!("Updated ProofPay Prover fixtures");
}
